Asp.NetMVC/Models/Address.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Asp.NetMVC.Models
{
    public class Address
    {
        public string AddressDefinition { get; set; }
        public string City { get; set; }
    }
}

Asp.NetMVC/Models/Message.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Asp.NetMVC.Models
{
    public class Message
    {
        public Guid Id { get; set; }
        public int Level { get; set; }
        public string Text { get; set; }
    }
}

Asp.NetMVC/Models/Person.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Asp.NetMVC.Models
{
    public class Person
    {
        public string Name { get; set; }
        public string Surname { get; set; }
        public int Age { get; set; }
    }
}

Asp.NetMVC/Controllers/BootstrapController.cs
using Asp.NetMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Asp.NetMVC.Controllers
{
    public class BootstrapController : Controller
    {
        // GET: Bootstrap
        public ActionResult HomePage()
        {
            return View();
        }
        public ActionResult HelperMethod()
        {
            return View();
        }
        public ActionResult CustomHelper()
        {
            List<Message> messages = new List<Message>();
            messages.Add(new Message { Level = 1, Text = "Uyarı mesajı" });
            messages.Add(new Message { Level = 2, Text = "Uyarı mesajı2" });
            messages.Add(new Message { Level = 3, Text = "Uyarı mesajı3" });
            return View(messages);
        }

        public ActionResult AnimasyonCheckBox()
        {
            return View();
        }
        
    }
}

Asp.NetMVC/Controllers/ControllerToViewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Asp.NetMVC.Controllers
{
    public class ControllerToViewController : Controller
    {
        // GET: ControllerToView
        public ActionResult Index()
        {
            //ViewData["FullName"] = "yunus önal";     //Viewdata ve viewbag yazım şekli farklı olsada kullanımı aynıdır.
            //ViewData["check"] = true;

            //TempData["FullName"] = "yunus önal";       tempdata ya farklı sayfalardan da ulaşılabilir. İkinci sayfaya kadar veriyi saklar.
            //TempData["Check"] = true;

            ViewBag.FullName = "Yunus ÖNAL";            //Viewbag ve viewdata veriyi sadece tek bir sayfada tutar. 
            ViewBag.Check = true;

            ViewBag.List = new SelectListItem[]
            {
                new SelectListItem() {Text = "Malatya"},
                new SelectListItem() {Text = "Diyarbakır"},
                new SelectListItem() {Text = "Ankara"},
                new SelectListItem() {Text = "İstanbul"}
            };
            return View();
        }

        public ActionResult HomePage()
        {
            return View();
        }

        [HttpPost]
        public ActionResult HomePage(string Name, bool Check, string list1)
        {
            //var n1 = Request.Form["Name"];
            //var l1 = Request.Form["list1"];
            //var c1 = Request.Form.GetValues("Check")[0];  //Seçili durumu başa alır. Checkbox işaretliyse True,False , işaretli değilse False,true yapar.
            return View();
        }
    }
}

Asp.NetMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Asp.NetMVC.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult RazorSyntax()
        {
            return View();
        }
        public ActionResult HtmlHelpers()
        {
            return View();
        }
       public ActionResult CustomHtmlHelpers()
        {
            return View();
        }
        public ActionResult UrlLink()
        {
            return View();
        }
        public ActionResult HttpUtility()
        {
            return View();
        }
    }
}

Asp.NetMVC/Controllers/ModelController.cs
using Asp.NetMVC.Models;
using Asp.NetMVC.ViewsModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Asp.NetMVC.Controllers
{
    public class ModelController : Controller
    {
        // GET: Model
        public ActionResult HomePage()
        {
            Person person = new Person();
            person.Name = "Yunus";
            person.Surname = "ÖNAL";
            person.Age = 25;

            Address address = new Address();
            address.AddressDefinition = "Deneme adresi.";
            address.City = "Malatya";

            HomePageViewModel mod = new HomePageViewModel();
            mod.Persons = person;
            mod.Addresss = address;
            return View(mod);
        }
        [HttpPost]
        public ActionResult HomePage(Person p)
        {
            return View(p);
        }
    }
}

Asp.NetMVC/Controllers/ViewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Asp.NetMVC.Controllers
{
    public class ViewsController : Controller
    {
        public ActionResult HomePage()
        {
            return View();
        }
        public ActionResult About()
        {
            return View();
        }
        public ActionResult Contact()
        {
            return View();
        }
        public ActionResult About2()
        {
            return View();
        }
        public ActionResult SectionLayout()
        {
            return View();
        }

    }
}

Asp.NetMVC/Views/Bootstrap/AnimasyonCheckBox.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AnimasyonCheckBox</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/AnimatedCheckbox.css" rel="stylesheet" />
</head>
<body>
    <div class=" container">
        <div class=" row">
            <div class="col-md-12">
                <h2>Animated Radio & Checkboxes With NoJS</h2>
                <hr />
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-horizontal">

                    <div class="form-group">
                        <label class="col-md-2 control-label">
                            Ödeme Durumu=
                        </label>
                        <div class="col-md-10 checkbox">
                            <label>
                                @Html.CheckBox("odendimi", false)
                                <span class="cr">
                                    <i class="cr-icon glyphicon glyphicon-ok"></i>
                                </span>
                                <span>Ödendi mi?</span>
                            </label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-2 control-label">
                            Borç Durumu=
                        </label>
                        <div class="col-md-10 checkbox">
                            <label>
                                @Html.CheckBox("borc", false)
                                <span class="cr">
                                    <i class="cr-icon glyphicon glyphicon-ok"></i>
                                </span>
                                <span>Borcu var mı?</span>
                            </label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-2 control-label">
                            Bakiye Durumu=
                        </label>
                        <div class="col-md-10 checkbox">
                            <label>
                                @Html.CheckBox("bakiye", false)
                                <span class="cr">
                                    <i class="cr-icon glyphicon glyphicon-ok"></i>
                                </span>
                                <span>Bakiye kontrol edildi mi?</span>
                            </label>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</body>
</html>

Asp.NetMVC/Views/Bootstrap/CustomHelper.cshtml
@using Asp.NetMVC.Library
@using Asp.NetMVC.Models
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CustomHelper</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <div class="container">
        <br />
        <br />
        @Html.Alert("alert1","info","Bu bir uyarıdır. Sayfada gezinirken asla kopyalama yapmayın!")
        <hr />

        @foreach (Message item in Model)
        {
            @Html.AlertFor(x=>item, new { title=item.Text,level=item.Level})
        }
    </div>
</body>
</html>

Asp.NetMVC/Views/Bootstrap/HelperMethod.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>HelperMethod</title>
</head>
<body>
    <div> 
        @MyHelperMethod.Input("Button1","Button","Gönder")
    </div>
    <div>
        @MyHelperMethod.Table("Table1",3,3,"Ad", "Soyad", "Yaş")
    </div>
</body>
</html>

Asp.NetMVC/Views/Bootstrap/HomePage.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>HomePage</title>

    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-2.2.0.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</head>
<body>
    <div>
        <h2 class="text-center">Hoşgeldiniz</h2>
    </div>

    <div class="container-fluid">
        @*Header*@
        <div class="row">
            <div class="col-xs-12">
                <nav class="navbar navbar-default">
                    <div class="container-fluid">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#menu" aria-expanded="false">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <a class="navbar-brand" href="#">Siteler</a>
                        </div>

                        <div class="collapse navbar-collapse" id="menu">
                            <ul class="nav navbar-nav">
                                <li><a href="/Bootstrap/HomePage">Ana Sayfa</a></li>
                                <li><a href="/Bootstrap/HomePage">Ana Sayfa 2</a></li>
                                <li><a href="/Bootstrap/HomePage">Ana Sayfa 3</a></li>

                            </ul>
                        </div>
                    </div>
                </nav>
            </div>


        </div>
        @*Body*@
        <div class="row">
            <div class="col-md-9">
                <h2>Makaleler</h2>
                <hr />

                <div class="panel panel-default">
                    <div class="panel-heading">
                        Panel heading without title
                    </div>
                    <div class="panel-body">
                        <p>
                            dizgi ve baskı endüstrisinde kullanılan mıgır metinlerdir. Lorem Ipsum, adı bilinmeyen bir matbaacının bir hurufat numune kitabı oluşturmak üzere bir yazı galerisini alarak karıştırdığı 1500'lerden beri endüstri standardı sahte metinler olarak kullanılmıştır.
                            @*<a href="#" class="btn btn-danger btn-xs">More...</a>*@
                            @MyHelperMethod.Button(val:"More...")
                        </p>
                    </div>
                    <div class="panel-footer">
                        @for (int i = 0; i < 3; i++)
                        {
                            @MyHelperMethod.Tag(text:"Hashtag"+i.ToString())
                        }
                        @*<span class="label label-warning">HashTag1</span>&nbsp;
                        <span class="label label-warning">HashTag2</span>&nbsp;
                        <span class="label label-warning">HashTag3</span>&nbsp;*@
                    </div>
                </div>


                <div class="panel panel-default">
                    <div class="panel-heading">
                        Panel heading without title
                    </div>
                    <div class="panel-body">
                        <p>
                            dizgi ve baskı endüstrisinde kullanılan mıgır metinlerdir. Lorem Ipsum, adı bilinmeyen bir matbaacının bir hurufat numune kitabı oluşturmak üzere bir yazı galerisini alarak karıştırdığı 1500'lerden beri endüstri standardı sahte metinler olarak kullanılmıştır.
                            @MyHelperMethod.Button(val: "More...")
                        </p>
                    </div>
                    <div class="panel-footer">
                        @for (int i = 0; i < 3; i++)
                        {
                            @MyHelperMethod.Tag(color: "primary", text: "Hashtag" + i.ToString())
                        }
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Panel heading without title
                    </div>
                    <div class="panel-body">
                        <p>
                            dizgi ve baskı endüstrisinde kullanılan mıgır metinlerdir. Lorem Ipsum, adı bilinmeyen bir matbaacının bir hurufat numune kitabı oluşturmak üzere bir yazı galerisini alarak karıştırdığı 1500'lerden beri endüstri standardı sahte metinler olarak kullanılmıştır.
                            @MyHelperMethod.Button(val: "More...")
                        </p>
                    </div>
                    <div class="panel-footer">
                        @for (int i = 0; i < 3; i++)
                        {
                            @MyHelperMethod.Tag(color: "danger", text: "Hashtag" + i.ToString())
                        }
                    </div>
                </div>

            </div>
            <div class="col-md-3">
                <h2>Kategoriler</h2>
                <hr />
                @*<ul>
                    <li>
                        <a href="#">Kategori</a>
                    </li>
                    <li>
                        <a href="#">Kategori2</a>
                    </li>
                    <li>
                        <a href="#">Kategori3</a>
                    </li>
                    <li>
                        <a href="#">Kategori4</a>
                    </li>
                </ul>*@

                @MyHelperMethod.LinkList("Link1","Kategori1", "Kategori2", "Kategori3", "Kategori4", "Kategori5")
            </div>

        </div>
        @*Footer*@
        <div class="row">
            <hr />
            <div class="col-md-4">
                <ul class="small">
                    <li><a href="#">contentcontent!</a></li>
                    <li><a href="#">contentcontent!</a></li>
                    <li><a href="#">contentcontent!</a></li>
                </ul>
            </div>
            <div class="col-md-4">
                <ul class="small">
                    <li><a href="#">contentcontent!</a></li>
                    <li><a href="#">contentcontent!</a></li>
                    <li><a href="#">contentcontent!</a></li>
                </ul>
            </div>
            <div class="col-md-4">
                <ul class="small">
                    <li><a href="#">content!content</a></li>
                    <li><a href="#">content!content</a></li>
                    <li><a href="#">content!content</a></li>
                </ul>
            </div>
            <hr />
            <div class="col-xs-12 text-center">
                <hr />
                <span class="small">
                    Tüm hakları saklıdır. &copy;
                </span>
            </div>
        </div>
    </div>
</body>
</html>

Asp.NetMVC/Views/ControllerToView/HomePage.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>HomePage</title>
</head>
<body>

    <div>
        @{
            SelectListItem[] List = new SelectListItem[4]
            {
            new SelectListItem() {Text="Yalova",Value="Y"}, @*Eğer value ları yazmamış olsaydık controller tarafından bize dönen değer text olacaktı.*@
            new SelectListItem() {Text="Aydın",Value="A"},
            new SelectListItem() {Text="Karabük",Value="K"},
            new SelectListItem() {Text="Ankara",Value="An"}
                                                            };
        }

        @using (Html.BeginForm())
        {
            @("İsim : ") @Html.TextBox("Name") <br /> <br />
            @("Şehir : ") @Html.DropDownList("list1", List) <br /><br />
            @("Onaylıyorum ") @Html.CheckBox("Check")
            <hr />
            <input type="submit" value="Gönder" />
        }
    </div>
</body>
</html>

Asp.NetMVC/Views/ControllerToView/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div>
        <h2>Kullanıcı Bilgileri</h2>
        <hr />
    </div>

    <div>
        @*<b>İsim Soyisim=</b> @ViewData["FullName"] <br />
        <b>Bool veri türü=</b>@ViewData["Check"] <br />*@

        @*<b>İsim Soyisim=</b> @TempData["FullName"] <br />
        <b>Bool veri türü=</b>@TempData["Check"] <br />*@

        <b>İsim Soyisim=</b> @ViewBag.FullName <br />
        <b>Bool veri türü=</b>@ViewBag.Check
    </div>
    <hr />
    <div>
        <b>İsim Soyisim=</b> @Html.TextBox("FullName")  <br />  @*parantez içine controller da yazdığımız viewbag ismini yazarsakta veriyi getirebiliriz. *@
        <b>Bool veri türü=</b>@Html.CheckBox("Check") <br />
        <b>Şehir seçim=</b>@Html.DropDownList("List")
    </div>
</body>
</html>

Asp.NetMVC/Views/Home/CustomHtmlHelpers.cshtml
@using Asp.NetMVC.Library
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CustomHtmlHelpers</title>
</head>
<body>
    <div>
        @Html.Button("btn1", ButtonType.button, "Tamam") <br /><br />
        @Html.Button("btn2", "btn btn-success", ButtonType.submit, "İptal")
        <hr />
        @Html.Paragraph("p1",5,"dashed",@<text> <b style="color:blue;">Custom html helper ile oluşturuldu.</b></text>)
    </div>
</body>
</html>

Asp.NetMVC/Views/Home/HtmlHelpers.cshtml
@{
    ViewBag.Title = "HtmlHelpers";
}

<h2>HtmlHelpers</h2>


@{
    ViewBag.Title = "HtmlHelpers";
}

<h2>HtmlHelpers</h2>

<style>
    .kirmizi {
        color: red;
    }
</style>

<input type="text" name="text1" id="text1" />  <br />
<input type="button" name="button1" id="button1" value="Tamam" /> <br /><br />
<a href="/Home/RazorSyntax">Razor örneklerine git</a> <br />

<hr />

@Html.ActionLink("RazorSyntax sayfasına git", "RazorSyntax", "Home", new { fullname = "yunusonal" }, new { title = "Yönlendirme Linki", @class = "kirmizi" }) <br /> <br />
@Html.Label("label1", "Adınız Soyadınız")
@Html.TextBox("text2") <br /><br />
@Html.Label("label1", "Özgeçmiş özetiniz")
@Html.TextArea("textarea1", "", 8, 20, null) <br />
<input type="button" name="button2" id="button2" value="Tamam" /> <br />

Asp.NetMVC/Views/Home/HttpUtility.cshtml
@{
    ViewBag.Title = "HttpUtility";
}

<h2>HttpUtility</h2>

@HttpUtility.HtmlEncode("<b>Yunus Önal</b>") <br /> @*html taglarını özel karakterlerle şifreler*@
@HttpUtility.HtmlDecode("&lt;b&gt;Yunus &#214;nal&lt;/b&gt;") <br /> @*Şifrelenmiş html taglarını normal karakterlere dönüştürür *@
<hr />
@Html.Raw("<b>Yunus Önal</b>") @*html taglarını göstermezken html taglarını görüntüleyebilirsiniz.*@
<hr />
@Html.Raw("<script type='text/javascript'>alert('Başarılı giriş '); </script>") 
<hr />
@Html.Raw("<style> h2 {color:blue;} </style>")

Asp.NetMVC/Views/Home/RazorSyntax.cshtml
@{
    ViewBag.Title = "RazorSyntax";
}

<h2>RazorSyntax</h2>

@{
    string name = "Yunus";
    string surname = "Önal";
    string fullname = name + " " + surname;

    <ul>
        <li>
            @name
        </li>
        <li>
            @surname
        </li>
        <li>
            <i>@fullname</i>
        </li>
    </ul>
}

<hr />

@name
<br />
@surname
<br />
<b>@fullname</b>

<hr />

@{
    string[] names = new string[4] { "Ali", "Veli", "Ayşe", "Senay" };
    int index = 0;

    <ul>
        @foreach (var name2 in names)
        {
            <li>
                @if (index % 2 == 0)
                {
                    @name2 <br />

                }
                else
                {
                    @name2
                }
            </li>
            index++;
        }
    </ul>
}
    <hr />

@for (int i = 0; i <= 10; i++)
{
    @("Sayı: " + i.ToString()) <br />
}

Asp.NetMVC/Views/Home/UrlLink.cshtml
@{
    ViewBag.Title = "UrlLink";
}

<h2>UrlLink</h2>

<a href="/Home/RazorSyntax">Razor View Engine görüntüle</a> <br /><br />
<hr />
@Html.ActionLink("Razor sayfasına git", "RazorSyntax", "Home",new { title="sayfaya git"}) <br />
<hr />
<a id="link1" name="link1" href=@Url.Action("RazorSyntax", "Home", null)>Url Action ile Razor sayfasına git</a>
<hr />
@Url.Action("HtmlHelpers") <br />
@Url.Content("~/Home/HtmlHelpers") <br />
@Url.Encode("~/Home/HtmlHelpers?arama=yunus önal") @*özel karakterlerin linki bozmaması adına encode kullanılır.*@

Asp.NetMVC/Views/Model/HomePage.cshtml
@model Asp.NetMVC.ViewsModels.HomePageViewModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>HomePage</title>
</head>
<body>
    <div>
        <h2>Ana Sayfa</h2>
        <hr />
    </div>
    <div>
        <b>Ad:</b> @Model.Persons.Name <br />
        <b>Soyad:</b> @Model.Persons.Surname <br />
        <b>Yaş:</b> @Model.Persons.Age
        <hr />
        <b>Ad Soyad:</b>@(Model.Persons.Name + " " + @Model.Persons.Surname)
        <hr />
        <b>Adres:</b>@(Model.Addresss.AddressDefinition + " / " + Model.Addresss.City))
    </div>
    <hr />
    <div>
        @using (Html.BeginForm())
        {
            <b>İsim:</b> @Html.TextBoxFor(model => model.Persons.Name)
            <b>Soyisim:</b> @Html.TextBoxFor(model => model.Persons.Surname)
            <b>Yaş:</b> @Html.TextBoxFor(model => model.Persons.Age)
            <b>Adres:</b> @Html.TextBoxFor(model => model.Addresss.AddressDefinition)
            <b>Şehir:</b> @Html.TextBoxFor(model => model.Addresss.City)

            <hr />

            <input type="submit" name="" value="Gönder" />
        }
    </div>
</body>
</html>

Asp.NetMVC/Views/Shared/_LayoutPage1.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <style>
        .block{
            display:block;
            margin:10px;
            border:2px dotted #0026ff;
            padding:10px;
        }
        .block2 {
            display: inline-block;
            margin: 5px;
            border: 2px dotted #b6ff00;
            padding: 10px;
        }
        #menu ul li{
            display:inline-block;
            width:100px;
            height:30px;
            text-align:center;
            border:1px solid #b6ff00;
            background-color:brown;
            margin:5px;
            line-height:30px;
            vertical-align:middle;
        }
        #menu a{
            color:aliceblue;
            text-decoration:none;
            font-size:smaller;
        }
        #menu li:hover{
            background-color:aquamarine;
        }
        #menu  li:hover{
            color:blue;
        }
    </style>

</head>
<body>
    <div id="menu" class="block">
        <ul>
            <li>@Html.ActionLink("Ana Sayfa","HomePage","Views")</li>
            <li>@Html.ActionLink("Hakkımızda","About","Views")</li>
            <li>@Html.ActionLink("İletişim","Contact","Views")</li>
        </ul>
    </div>

    <div class="block">
        @RenderBody()
    </div>

    <div class="block">
        <b>Tüm hakları saklıdır. &copy;</b>
    </div>
</body>
</html>

Asp.NetMVC/Views/Shared/_LayoutPage2.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <style>
        .block {
            display: block;
            margin: 10px;
            border: 2px dotted #0026ff;
            padding: 10px;
        }

        #menu ul li {
            display: inline-block;
            width: 100px;
            height: 30px;
            text-align: center;
            border: 1px solid #b6ff00;
            background-color: brown;
            margin: 5px;
            line-height: 30px;
            vertical-align: middle;
        }

        #menu a {
            color: aliceblue;
            text-decoration: none;
            font-size: smaller;
        }

        #menu li:hover {
            background-color: aquamarine;
        }

        #menu li:hover {
            color: blue;
        }
    </style>

</head>
<body>
    <div class="block">
        <h2>Yunus Önal blog sitesi </h2><hr />
        <h4>Her gün yeni bir bilgi.</h4>
    </div>

    <div class="block">
        <p>Önümüzde uzun bir yol var. Daha azimli ve istekli çalışacağız.</p>
    </div>

    <div class="block">
        @RenderBody()
    </div>

    <div id="menu" class="block">
        <ul>
            <li>@Html.ActionLink("Ana Sayfa", "HomePage", "Views")</li>
            <li>@Html.ActionLink("Hakkımızda", "About", "Views")</li>
            <li>@Html.ActionLink("İletişim", "Contact", "Views")</li>
        </ul>
    </div>

    <div class="block">
        <b>Tüm hakları saklıdır. &copy;</b>
    </div>
</body>
</html>

Asp.NetMVC/Views/Shared/_LayoutPage3.cshtml
@{
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

<div class="block2" style="width:660px;">
    @RenderBody()
</div>

<div class="block2" style="float:right;">
    <h4>Yapmış olduğumuz çalışmalar</h4>
    <ul>
        <li>Kurumsal web siteleri</li>
        <li>Yazılım destek ekibi</li>
        <li>Eğitim destek sisteemleri</li>
    </ul>
</div>

Asp.NetMVC/Views/Shared/_LayoutPage4.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <style>
        .block {
            display: block;
            margin: 10px;
            border: 2px dotted #0026ff;
            padding: 10px;
        }

        .block2 {
            display: inline-block;
            margin: 5px;
            border: 2px dotted #b6ff00;
            padding: 10px;
        }

        #menu ul li {
            display: inline-block;
            width: 100px;
            height: 30px;
            text-align: center;
            border: 1px solid #b6ff00;
            background-color: brown;
            margin: 5px;
            line-height: 30px;
            vertical-align: middle;
        }

        #menu a {
            color: aliceblue;
            text-decoration: none;
            font-size: smaller;
        }

        #menu li:hover {
            background-color: aquamarine;
        }

        #menu li:hover {
            color: blue;
        }
    </style>

</head>
<body>
    <div id="menu" class="block">
        <ul>
            <li>@Html.ActionLink("Ana Sayfa", "HomePage", "Views")</li> @*sabit link burada duracak*@
                 @RenderSection("Link",false)                           @*ihtiyaç halinde header kısmını bozmadan yeni bir Link yazılabilir.*@
        </ul>
    </div>

    <div class="block">
        @RenderBody()
    </div>

    <div class="block">
        @RenderSection("Footer",false) @*Her sayfaya ekstra footer eklemek istemiyorsanız false yapabilirsiniz.*@
        <br />
        <b>Tüm hakları saklıdır. &copy;</b>
    </div>
</body>
</html>

Asp.NetMVC/Views/Shared/_PartialOtherLink.cshtml
<h4>Bu sayfalara bakabilirsiniz.</h4>  @*Partial view ler aynı sayfadaki linklerin birden fazla kullanıldığı durumlarda kullanılabilir.*@
<hr />
<ul>
    <li><a href="#">Mvc</a></li>
    <li><a href="#">Yazılım Dünyası</a></li>
    <li><a href="#">Silikon Vadisi</a></li>
</ul>